<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Test_MainFSM" Id="{d73df427-cc73-4c5c-8bd4-affee78edae7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Test_MainFSM EXTENDS TcUnit.FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>