<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_Test_FSM" Id="{eca0fa74-05f4-43bc-bf21-8752642e406c}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Test_FSM EXTENDS TcUnit.FB_TestSuite
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>